<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit81a63c3c768438babf16aa9cc82d5a4d
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stripe\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/stripe/stripe-php/lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit81a63c3c768438babf16aa9cc82d5a4d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit81a63c3c768438babf16aa9cc82d5a4d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit81a63c3c768438babf16aa9cc82d5a4d::$classMap;

        }, null, ClassLoader::class);
    }
}
